os: osx
osx_image: xcode10.2
language: swift
xcode_project: Wumpus.xcodeproj
xcode_scheme: Wumpus
xcode_destination: platform=macOS

before_script:
- security create-keychain -p travis ios-build.keychain
- security default-keychain -s ios-build.keychain
- security unlock-keychain -p travis ios-build.keychain
- security import ./Provisioning/certs/apple.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
- security import ./Provisioning/certs/distribution.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
- security import ./Provisioning/certs/distribution.p12 -k ~/Library/Keychains/ios-build.keychain -P $KEY_PASSWORD -T /usr/bin/codesign
- security set-key-partition-list -S apple-tool:,apple: -s -k travis ios-build.keychain
